from bdd.tipos import *
from bdd.errores import *
from bdd.utiles import *

@runtime_checkable
class ProtocoloBaseDeDatos(Protocol):
    def DESCRIBE(self: Self, base_de_datos:str, tabla :str) -> Self: ...
    
    def SELECT(self: Self, *columnas : str) -> Self: ...
    def FROM(self: Self, tabla : str) -> Self: ...
    def JOIN(self: Self, tipo: TipoJoin, tabla: str, columna_origen : str, columna_destino: str) -> Self: ...
    def WHERE(self: Self, **columnas : Unpack[dict[str,any]]) -> Self: ...
    def LIMIT(self: Self, desplazamiento : int, cantidad: int) -> Self: ...
    
    def UPDATE(self: Self, tabla: str) -> Self: ...
    def INSERT(self: Self, tabla: str) -> Self: ...
    def SET(self: Self, **valores : Unpack[dict[str,any]]) -> Self: ...

    def Ejecutar(self: Self) -> Self :...
    def DevolverUnResultado(self: Self) -> Resultado :...
    def DevolverResultados(self: Self) -> tuple[Resultado] :...
    def DevolverIdUltimaInsercion(self:Self) -> int :...

class BaseDeDatos_MySQL: ...